spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: none
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100
  profiles:
    active:
      - dev
---
spring:
  profiles: prod
  datasource:
    url: jdbc:h2:./grimacegram-prod
    username: sa
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: false
grimacegram:
  upload-path: uploads-prod
---
spring:
 profiles: dev
 datasource:
   url: jdbc:h2:mem:grimacegram-dev
grimacegram:
  upload-path: uploads-dev
---
spring:
  profiles: test
grimacegram:
  upload-path: uploads-test
